[build]
  # Comando para build (não necessário para sites estáticos)
  command = "echo 'No build command required'"
  
  # Diretório que será publicado
  publish = "."
  
  # Configurações para Flask (caso queira usar Netlify Functions)
  functions = "netlify/functions"

[build.environment]
  # Versão do Python (caso necessário)
  PYTHON_VERSION = "3.9"

# Redirecionamentos para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache para assets estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"